"""
Curated skill taxonomy — ~200 normalized tech skill names.

Used by the parser to:
  1. Match extracted tokens against known skills (case-insensitive).
  2. Return the canonical form (e.g., "javascript" → "JavaScript").
"""

from __future__ import annotations

# Maps lowercase token → canonical display name
SKILL_MAP: dict[str, str] = {
    # Languages
    "python": "Python",
    "java": "Java",
    "javascript": "JavaScript",
    "typescript": "TypeScript",
    "go": "Go",
    "golang": "Go",
    "rust": "Rust",
    "c++": "C++",
    "cpp": "C++",
    "c#": "C#",
    "csharp": "C#",
    "kotlin": "Kotlin",
    "swift": "Swift",
    "ruby": "Ruby",
    "php": "PHP",
    "scala": "Scala",
    "r": "R",
    "matlab": "MATLAB",
    "perl": "Perl",
    "bash": "Bash",
    "shell": "Shell Scripting",
    "powershell": "PowerShell",
    "elixir": "Elixir",
    "haskell": "Haskell",
    "lua": "Lua",
    "dart": "Dart",
    "julia": "Julia",
    "groovy": "Groovy",
    "cobol": "COBOL",
    "fortran": "Fortran",
    # Web frontend
    "react": "React",
    "reactjs": "React",
    "react.js": "React",
    "vue": "Vue.js",
    "vuejs": "Vue.js",
    "vue.js": "Vue.js",
    "angular": "Angular",
    "angularjs": "AngularJS",
    "svelte": "Svelte",
    "next.js": "Next.js",
    "nextjs": "Next.js",
    "nuxt": "Nuxt.js",
    "nuxtjs": "Nuxt.js",
    "gatsby": "Gatsby",
    "html": "HTML",
    "html5": "HTML5",
    "css": "CSS",
    "css3": "CSS3",
    "sass": "Sass",
    "scss": "Sass",
    "less": "Less",
    "tailwind": "Tailwind CSS",
    "tailwindcss": "Tailwind CSS",
    "bootstrap": "Bootstrap",
    "material ui": "Material UI",
    "mui": "Material UI",
    "webpack": "Webpack",
    "vite": "Vite",
    "redux": "Redux",
    "mobx": "MobX",
    "graphql": "GraphQL",
    "apollo": "Apollo GraphQL",
    # Web backend
    "node.js": "Node.js",
    "nodejs": "Node.js",
    "express": "Express.js",
    "expressjs": "Express.js",
    "fastapi": "FastAPI",
    "django": "Django",
    "flask": "Flask",
    "spring": "Spring",
    "spring boot": "Spring Boot",
    "spring mvc": "Spring MVC",
    "rails": "Ruby on Rails",
    "laravel": "Laravel",
    "nestjs": "NestJS",
    "asp.net": "ASP.NET",
    "dotnet": ".NET",
    ".net": ".NET",
    "gin": "Gin",
    "fiber": "Fiber",
    "grpc": "gRPC",
    "rest": "REST APIs",
    "restful": "REST APIs",
    "rest api": "REST APIs",
    "graphql api": "GraphQL",
    "websocket": "WebSockets",
    # Databases
    "postgresql": "PostgreSQL",
    "postgres": "PostgreSQL",
    "mysql": "MySQL",
    "mariadb": "MariaDB",
    "sqlite": "SQLite",
    "mssql": "SQL Server",
    "sql server": "SQL Server",
    "oracle db": "Oracle DB",
    "mongodb": "MongoDB",
    "redis": "Redis",
    "elasticsearch": "Elasticsearch",
    "cassandra": "Cassandra",
    "dynamodb": "DynamoDB",
    "firestore": "Firestore",
    "couchdb": "CouchDB",
    "neo4j": "Neo4j",
    "influxdb": "InfluxDB",
    "clickhouse": "ClickHouse",
    "sql": "SQL",
    "nosql": "NoSQL",
    "orm": "ORM",
    "hibernate": "Hibernate",
    "sequelize": "Sequelize",
    "prisma": "Prisma",
    # Cloud & DevOps
    "aws": "AWS",
    "amazon web services": "AWS",
    "gcp": "GCP",
    "google cloud": "GCP",
    "azure": "Azure",
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "k8s": "Kubernetes",
    "helm": "Helm",
    "terraform": "Terraform",
    "ansible": "Ansible",
    "jenkins": "Jenkins",
    "gitlab ci": "GitLab CI",
    "github actions": "GitHub Actions",
    "circleci": "CircleCI",
    "travis ci": "Travis CI",
    "ci/cd": "CI/CD",
    "devops": "DevOps",
    "sre": "SRE",
    "nginx": "Nginx",
    "apache": "Apache",
    "linux": "Linux",
    "unix": "Unix",
    "pulumi": "Pulumi",
    "cloudformation": "CloudFormation",
    "cdn": "CDN",
    "load balancer": "Load Balancing",
    # ML / Data
    "machine learning": "Machine Learning",
    "ml": "Machine Learning",
    "deep learning": "Deep Learning",
    "dl": "Deep Learning",
    "nlp": "NLP",
    "natural language processing": "NLP",
    "computer vision": "Computer Vision",
    "pytorch": "PyTorch",
    "tensorflow": "TensorFlow",
    "keras": "Keras",
    "scikit-learn": "scikit-learn",
    "sklearn": "scikit-learn",
    "xgboost": "XGBoost",
    "lightgbm": "LightGBM",
    "pandas": "Pandas",
    "numpy": "NumPy",
    "scipy": "SciPy",
    "matplotlib": "Matplotlib",
    "seaborn": "Seaborn",
    "plotly": "Plotly",
    "hugging face": "Hugging Face",
    "transformers": "Transformers",
    "llm": "LLMs",
    "mlops": "MLOps",
    "spark": "Apache Spark",
    "apache spark": "Apache Spark",
    "hadoop": "Hadoop",
    "kafka": "Apache Kafka",
    "apache kafka": "Apache Kafka",
    "airflow": "Apache Airflow",
    "dbt": "dbt",
    "snowflake": "Snowflake",
    "databricks": "Databricks",
    "sagemaker": "SageMaker",
    "vertex ai": "Vertex AI",
    "data engineering": "Data Engineering",
    "data science": "Data Science",
    "etl": "ETL",
    "tableau": "Tableau",
    "power bi": "Power BI",
    # Security
    "oauth": "OAuth",
    "oauth2": "OAuth 2.0",
    "jwt": "JWT",
    "saml": "SAML",
    "ssl": "SSL/TLS",
    "tls": "SSL/TLS",
    "pen testing": "Penetration Testing",
    "penetration testing": "Penetration Testing",
    "soc 2": "SOC 2",
    "gdpr": "GDPR",
    "owasp": "OWASP",
    # Testing
    "unit testing": "Unit Testing",
    "integration testing": "Integration Testing",
    "tdd": "TDD",
    "bdd": "BDD",
    "pytest": "pytest",
    "jest": "Jest",
    "cypress": "Cypress",
    "playwright": "Playwright",
    "selenium": "Selenium",
    "junit": "JUnit",
    "mockito": "Mockito",
    # Architecture
    "microservices": "Microservices",
    "event-driven": "Event-Driven Architecture",
    "cqrs": "CQRS",
    "ddd": "Domain-Driven Design",
    "domain-driven design": "Domain-Driven Design",
    "solid": "SOLID Principles",
    "design patterns": "Design Patterns",
    # Tools & Misc
    "git": "Git",
    "github": "GitHub",
    "gitlab": "GitLab",
    "jira": "Jira",
    "confluence": "Confluence",
    "agile": "Agile",
    "scrum": "Scrum",
    "kanban": "Kanban",
    "figma": "Figma",
    "postman": "Postman",
    "swagger": "Swagger / OpenAPI",
    "openapi": "Swagger / OpenAPI",
    "linux administration": "Linux Administration",
    "excel": "Excel",
    "tableau": "Tableau",
}

# Ordered list of all canonical skill names (for display / iteration)
ALL_SKILLS: list[str] = sorted(set(SKILL_MAP.values()))


def normalize_skill(raw: str) -> str | None:
    """
    Normalize a raw skill token to its canonical form.
    Returns None if the token is not in the taxonomy.
    """
    return SKILL_MAP.get(raw.strip().lower())


def normalize_skill_list(raw_skills: list[str]) -> list[str]:
    """
    Normalize a list of raw skill strings, deduplicating and returning only
    skills that are in the taxonomy in their canonical form.
    """
    seen: set[str] = set()
    result: list[str] = []
    for raw in raw_skills:
        canonical = normalize_skill(raw)
        if canonical and canonical not in seen:
            seen.add(canonical)
            result.append(canonical)
    return result
